import pandas as pd
new=pd.read_csv(r"C:\Users\astha\Downloads\sales-data-sample.csv")
print(new)
new1=new.head()
print(new1)
print(new.duplicated())
print(new.to_string)
new2=new.dropna(inplace=True)
print(new2)
# Total Sales Revenue
total_sale = new['Sales'].sum()
print(f"Total Sales: ${total_sale}")
 #Number of Orders
total_profit=new["Profit"].sum()
print(f"total profit:{total_profit}")
print(new["Sales"].dtype)
print(new.shape) 
print(new.columns.tolist()) 
new.columns = new.columns.str.strip()
print(new["Sales"].isnull().sum())
top_products = new.groupby('ProductName')['Sales'].sum().sort_values(ascending=False).head(10)
print(top_products)
